CXX=clang++
CC=$(CXX)
CXXFLAGS=--std=c++1y -stdlib=libc++ -Wall -I/home/mathias/projects/ericniebler-range-v3/include
LDFLAGS=--std=c++1y -stdlib=libc++ 

all: intersect intersect-range adaptor func

intersect.o: intersect.cpp

intersect-range.o: intersect-range.cpp

adaptor.o: adaptor.cpp
