CXXFLAGS=-std=c++11 -O3 -g

all:
	cd src && make $@
	cd test && make $@

.PHONY: clean test benchmark

clean:
	cd src && make $@
	cd test && make $@

benchmark:
	cd src && make $@

test:
	cd test && make $@
